import jsPDF from 'jspdf';
import type { ConversationMessage } from '@/lib/storage/conversation-history';

interface ExportOptions {
  title: string;
  useCase: string;
  messages: ConversationMessage[];
  language: 'es' | 'en';
  date?: string;
}

const LABELS = {
  es: {
    header: 'UtopIA | Consultoría Contable & Tributaria',
    reportTitle: 'Reporte de Consulta',
    caseType: 'Tipo de caso',
    date: 'Fecha',
    conversation: 'Conversación',
    user: 'Usuario',
    assistant: 'Asistente',
    disclaimer:
      'AVISO PROFESIONAL: Este documento fue generado por UtopIA, una herramienta de asistencia profesional potenciada por IA. No constituye asesoría profesional certificada. Toda recomendación debe ser validada por un contador público certificado. Cumplimos con la Ley 1581 de Protección de Datos.',
    page: 'Página',
  },
  en: {
    header: 'UtopIA | Accounting & Tax Consulting',
    reportTitle: 'Consultation Report',
    caseType: 'Case type',
    date: 'Date',
    conversation: 'Conversation',
    user: 'User',
    assistant: 'Assistant',
    disclaimer:
      'PROFESSIONAL NOTICE: This document was generated by UtopIA, an AI-powered professional assistance tool. It does not constitute certified professional advice. All recommendations should be validated by a certified public accountant. We comply with Law 1581 on Data Protection.',
    page: 'Page',
  },
};

export function exportConversationPDF(options: ExportOptions): void {
  const { title, useCase, messages, language, date } = options;
  const l = LABELS[language];
  const exportDate = date ?? new Date().toLocaleDateString(language === 'es' ? 'es-CO' : 'en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  function addPageFooter(pageNum: number) {
    doc.setFontSize(7);
    doc.setTextColor(120, 120, 120);
    doc.text(
      `${l.page} ${pageNum}`,
      pageWidth - margin,
      pageHeight - 10,
      { align: 'right' }
    );
    doc.text('utopia-ai.co', margin, pageHeight - 10);
  }

  function checkPageBreak(needed: number) {
    if (y + needed > pageHeight - 30) {
      addPageFooter(doc.getNumberOfPages());
      doc.addPage();
      y = margin;
    }
  }

  // ---- Header ----
  // Gold accent bar
  doc.setFillColor(212, 160, 23);
  doc.rect(0, 0, pageWidth, 3, 'F');

  // Brand
  doc.setFontSize(10);
  doc.setTextColor(212, 160, 23);
  doc.text(l.header, margin, y + 10);

  // Title
  y += 20;
  doc.setFontSize(18);
  doc.setTextColor(30, 58, 95);
  doc.text(l.reportTitle, margin, y);

  // Subtitle
  y += 8;
  doc.setFontSize(11);
  doc.setTextColor(80, 80, 80);
  doc.text(title, margin, y);

  // Meta info
  y += 10;
  doc.setFontSize(9);
  doc.setTextColor(100, 100, 100);
  doc.text(`${l.caseType}: ${useCase}`, margin, y);
  y += 5;
  doc.text(`${l.date}: ${exportDate}`, margin, y);

  // Divider
  y += 8;
  doc.setDrawColor(212, 160, 23);
  doc.setLineWidth(0.5);
  doc.line(margin, y, pageWidth - margin, y);
  y += 10;

  // ---- Conversation ----
  doc.setFontSize(12);
  doc.setTextColor(30, 58, 95);
  doc.text(l.conversation, margin, y);
  y += 8;

  for (const msg of messages) {
    const isUser = msg.role === 'user';
    const roleLabel = isUser ? l.user : l.assistant;

    checkPageBreak(20);

    // Role label
    doc.setFontSize(9);
    doc.setTextColor(isUser ? 212 : 30, isUser ? 160 : 58, isUser ? 23 : 95);
    doc.setFont('helvetica', 'bold');
    doc.text(roleLabel, margin, y);
    y += 5;

    // Message content
    doc.setFontSize(9);
    doc.setTextColor(50, 50, 50);
    doc.setFont('helvetica', 'normal');

    // Split long text into lines
    const lines = doc.splitTextToSize(msg.content, contentWidth);
    for (const line of lines) {
      checkPageBreak(5);
      doc.text(line, margin, y);
      y += 4.5;
    }

    y += 4;
  }

  // ---- Disclaimer Footer ----
  checkPageBreak(30);
  y += 5;
  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.3);
  doc.line(margin, y, pageWidth - margin, y);
  y += 6;

  doc.setFontSize(7);
  doc.setTextColor(140, 140, 140);
  const disclaimerLines = doc.splitTextToSize(l.disclaimer, contentWidth);
  for (const line of disclaimerLines) {
    checkPageBreak(4);
    doc.text(line, margin, y);
    y += 3.5;
  }

  // Page footers
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    addPageFooter(i);
  }

  // Download
  const safeTitle = title.replace(/[^a-zA-Z0-9]/g, '_').slice(0, 40);
  doc.save(`UtopIA_${safeTitle}_${Date.now()}.pdf`);
}
