-- Recovery migration for commit df9fc19 ("feat(pyme): nuevo modulo Contabilidad Pyme con OCR Vision")
-- which added pyme_* tables to src/lib/db/schema.ts but never produced an SQL migration file.
-- Hand-written (NOT generated by drizzle-kit) so it remains stable while parallel agents run in
-- Ola 0. Idempotent ALTER at the end recovers `repair_adjustments.period` drift left over from
-- the multiperiod refactor (see 0002_repair_sessions.sql vs schema.ts comment).
CREATE TABLE "pyme_books" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"workspace_id" uuid NOT NULL,
	"name" text NOT NULL,
	"currency" text DEFAULT 'COP' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pyme_uploads" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"book_id" uuid NOT NULL,
	"image_url" text NOT NULL,
	"mime_type" text NOT NULL,
	"page_count" integer DEFAULT 1 NOT NULL,
	"ocr_status" text DEFAULT 'pending' NOT NULL,
	"error_message" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pyme_entries" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"book_id" uuid NOT NULL,
	"upload_id" uuid,
	"entry_date" timestamp with time zone NOT NULL,
	"description" text NOT NULL,
	"kind" text NOT NULL,
	"amount" numeric(20, 2) NOT NULL,
	"category" text,
	"puc_hint" text,
	"source_image_url" text,
	"source_page" integer,
	"raw_ocr_text" text,
	"confidence" numeric(4, 3),
	"status" text DEFAULT 'draft' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pyme_categories" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"book_id" uuid NOT NULL,
	"name" text NOT NULL,
	"kind" text NOT NULL,
	"puc_hint" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "pyme_books" ADD CONSTRAINT "pyme_books_workspace_id_workspaces_id_fk" FOREIGN KEY ("workspace_id") REFERENCES "public"."workspaces"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pyme_uploads" ADD CONSTRAINT "pyme_uploads_book_id_pyme_books_id_fk" FOREIGN KEY ("book_id") REFERENCES "public"."pyme_books"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pyme_entries" ADD CONSTRAINT "pyme_entries_book_id_pyme_books_id_fk" FOREIGN KEY ("book_id") REFERENCES "public"."pyme_books"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pyme_entries" ADD CONSTRAINT "pyme_entries_upload_id_pyme_uploads_id_fk" FOREIGN KEY ("upload_id") REFERENCES "public"."pyme_uploads"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pyme_categories" ADD CONSTRAINT "pyme_categories_book_id_pyme_books_id_fk" FOREIGN KEY ("book_id") REFERENCES "public"."pyme_books"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "pyme_books_workspace_created_idx" ON "pyme_books" ("workspace_id","created_at" DESC);--> statement-breakpoint
CREATE INDEX "pyme_uploads_book_created_idx" ON "pyme_uploads" ("book_id","created_at");--> statement-breakpoint
CREATE INDEX "pyme_entries_book_date_idx" ON "pyme_entries" ("book_id","entry_date");--> statement-breakpoint
CREATE INDEX "pyme_entries_book_status_kind_date_idx" ON "pyme_entries" ("book_id","status","kind","entry_date");--> statement-breakpoint
ALTER TABLE "repair_adjustments" ADD COLUMN IF NOT EXISTS "period" text;
