-- Ola 8 — Nómina simple Pyme + historial de la calculadora RST/Ordinario.
-- Hand-written (NOT generated by drizzle-kit): meta/ solo tiene snapshots
-- hasta 0006, así que db:generate produciría duplicados de 0007-0013 (ver
-- advertencia en README). Mismo patrón manual que 0003_pyme_tables.sql.
CREATE TABLE IF NOT EXISTS "pyme_empleados" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"workspace_id" uuid NOT NULL,
	"nombre" text NOT NULL,
	"tipo" text DEFAULT 'empleado' NOT NULL,
	"cargo" text,
	"tipo_contrato" text,
	"salario_cop" numeric(14, 2) NOT NULL,
	"eps" text,
	"afp" text,
	"arl" text,
	"arl_clase" integer DEFAULT 1,
	"activo" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "pyme_empleados" ADD CONSTRAINT "pyme_empleados_workspace_id_workspaces_id_fk" FOREIGN KEY ("workspace_id") REFERENCES "public"."workspaces"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "pe_ws_idx" ON "pyme_empleados" USING btree ("workspace_id","activo");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "pyme_tax_calculations" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"workspace_id" uuid NOT NULL,
	"annual_sales_cop" numeric(20, 2) NOT NULL,
	"rst_group" text NOT NULL,
	"rst_cop" numeric(20, 2) NOT NULL,
	"ordinario_cop" numeric(20, 2) NOT NULL,
	"recommended" text NOT NULL,
	"savings_cop" numeric(20, 2) NOT NULL,
	"semaforo_level" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "pyme_tax_calculations" ADD CONSTRAINT "pyme_tax_calculations_workspace_id_workspaces_id_fk" FOREIGN KEY ("workspace_id") REFERENCES "public"."workspaces"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "ptc_ws_idx" ON "pyme_tax_calculations" USING btree ("workspace_id","created_at");
